### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by tomitrescak** [djkf/jest-sinon#14]
Hi, thanks for the great package. an error messages be somehow improved? Following is not very helpful:

```
done() called multiple times in test <Component > Schedule > Subscription shows subscription> of file .\src\components\Schedules\tests\ScheduleSubscription.test.js; in addition, done() received error: JestAssertionError: expect(sinon.spy).toBeCalledWith() 
 
Expected spy to have "been called with correct arguments", instead received a spy that has "not been called with correct arguments" 
    at _callee$ (.\src\components\Schedules\tests\ScheduleSubscription.test.js:32:63) 
    at tryCatch (.\node_modules\regenerator-runtime\runtime.js:63:40) 
    at Generator.invoke [as _invoke] (.\node_modules\regenerator-runtime\runtime.js:293:22) 
    at Generator.next (.\node_modules\regenerator-runtime\runtime.js:118:21) 
    at asyncGeneratorStep (.\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24) 
    at _next (.\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) { 
  matcherResult: [Object] 
} 
```

**Comment by djkf** [comment]
Hi @tomitrescak,

Thanks for raising this. The error messages were always very rushed and could do with some improvement. I'll see if I can dedicate some time to making them more useful.

Feel free to suggest any ideas you might have in improving them.

Cheers,

**Comment by tomitrescak** [comment]
Hi, if we can see the error messages coming from `sinon.assert` would be as good as it gets.

**Comment by cabnnt** [comment]
@djkf is this something that is still on your radar? if not, i could look into making a pull request

**Comment by djkf** [comment]
Hey! 👋 Sorry, I let this repo get a little abandoned over the last few years. I'm happy to have external contributions, feel free to raise a PR.

In the meantime I've fixed a couple of odd issues that have arisen over time. The tests on the main branch should now pass once again.

I will see if I can maintain it better in the future. Thanks for the reminder 😆 👍 

Hope this helps.

**Comment by rluvaton** [comment]
I've created a package https://github.com/rluvaton/sinon-jest-matchers with the same output as jest to solve this issue

**Comment by djkf** [comment]
awesome work @rluvaton! Let me know if you want a mention as an alternative in the README.

**Comment by rluvaton** [comment]
Sounds great man!
